[package]
name = "idp"
version = "0.1.0"
authors = ["Victor Dods <victor.dods@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# This crate really just combines the separate idp_* crates into one.
# TODO: Add a feature for each sub-crate.
[dependencies]
idp_client = { path = "../idp_client" }
idp_core = { path = "../idp_core" }
idp_proto = { path = "../idp_proto" }
idp_server = { path = "../idp_server" }

[dev-dependencies]
anyhow = "1.0.69"
env_logger = "0.8.4"
log = "0.4.14"
parking_lot = "0.12.1"
tokio = { version = "1.25.0", features = [
    "rt-multi-thread",
    "time",
    "fs",
    "macros",
    "net",
] }
tonic = { version = "0.8.3", features = ["tls"] }
uuid = { version = "0.8.2", features = ["v4"] }
