[package]
name = "idp_proto"
version = "0.0.0"
authors = ["Victor Dods <victor.dods@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.7", features = ["sqlite"] }
failure = "0.1.8"
prost = "0.7.0"
serde = { version = "1.0.126", features = ["derive"] }
sha2 = "0.9.5"
tonic = { version = "0.4.3", features = ["tls"] }

# This is for building protobufs and GRPC service from .proto files
[build-dependencies]
tonic-build = { version = "0.4.2", features = ["prost"] }
